### ISSUE TITLE
Connecting IPeppolReportingBackendSPI with StatisticsReport

### ISSUE THREAD

**Issue by iansmirlis** [phax/peppol-reporting#2]
Hello 

It seems that the only way to get data from the backend is via this function
https://github.com/phax/peppol-reporting/blob/298aea8bc410648e9a82b57cb1d295b5e1a70ba7/peppol-reporting-api/src/main/java/com/helper/peppol/reporting/api/backend/IPeppolReportingBackendSPI.java#L101-L103

And in order to generate statistics, i.e EndUserStatisticsReport, it's expected to pass an Iterable<>:
https://github.com/phax/peppol-reporting/blob/298aea8bc410648e9a82b57cb1d295b5e1a70ba7/peppol-reporting/src/main/java/com/helper/peppol/reporting/eusr/EndUserStatisticsReport.java#L284-L287

Java is not my cup of tea, but it seems to me that the only way to generate the report is to load all the PeppolReportingItem into a list and pass them to the report generator.

I think it would be useful for the backend to also provide an Iterable<> via a function in order to iterate the data through pages returned by the database, without loading all the data into memory.

Thanks

**Comment by phax** [comment]
Thanks, good suggestion - will add it accordingly.
